### ISSUE TITLE
Tables won't load for many data sets

### ISSUE THREAD

**Issue by astrong19** [wri/odp_front_end#1]
The tables won't load for many of the data sets in the ODP. @jnordling @tedrick any ideas what's going on here? Problem with the javascript code?

Here are some exmaples: 

http://data.globalforestwatch.org/datasets/ed8d5951b2a4482a9e62c4fe0bc23b5f_27?uiTab=table

http://data.globalforestwatch.org/datasets/baae47df61ed4a73a6f54f00cb4207e0_5?uiTab=table

http://data.globalforestwatch.org/datasets/573ce69e9c0f486dbbad021317de7bab_14?uiTab=table

**Comment by astrong19** [comment]
@adammulligan @mbarrenechea @apercas Any thoughts on what's causing this issue? A couple errors I see when inspecting are:

TypeError: Slick.Grid is not a constructor

Error in parsing value for 'transition'.  Declaration dropped.

downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://open-data-prod-ui.s3.amazonaws.com/latest/fonts/bootstrap/glyphicons-halflings-regular.woff2

**Comment by tedrick** [comment]
Tracked the issue down.  There is a namespace conflict between 2 libraries:
1) SlickGrid (https://github.com/mleibman/SlickGrid) - this is the library that develops the table
2) Slick carousel (http://kenwheeler.github.io/slick/) - this is loaded from gfw-assets.js 

Both of these attempt to use the variable 'Slick'

**Comment by adammulligan** [comment]
We've actually replaced Slick in our latest version of GFW-assets (the navbar), so once that's deployed to production in the next couple weeks, the issue should hopefully be solved :-)

**Comment by astrong19** [comment]
Thanks @adammulligan, will the changes be deployed to this repo?

**Comment by tedrick** [comment]
The gfw-assets file is being called externally from the code in the repo, so no changes to this repo will be necessary for that.

**Comment by adammulligan** [comment]
@astrong19 Yep, @tedrick is correct. I'll post a note here when it's deployed so you can test it.

**Comment by astrong19** [comment]
Thanks both!

**Comment by tedrick** [comment]
Given that the solution is identified, please close the issue

**Comment by astrong19** [comment]
@adammulligan Any updates on the deploy of GFW-assets?

**Comment by adammulligan** [comment]
@astrong19 yep, we deployed on Friday and everything is working on our end, so please test it out and let me know if you have any problems :+1:

**Comment by astrong19** [comment]
@adammulligan Nice love it! Working well in chrome, but having a few issues in Firefox. I'll move the convo to basecamp and close this issue.
