### ISSUE TITLE
Share button on results and details page is broken

### ISSUE THREAD

**Issue by astrong19** [wri/odp_front_end#3]
@jnordling @tedrick thoughts on how to fix the share button links on the results and details page of the ODP? Picture attached as fyi
![share button](https://cloud.githubusercontent.com/assets/8313799/12734766/939ebbc4-c910-11e5-90eb-fd0dbfdb732d.JPG)

**Comment by tedrick** [comment]
We may need to check what the original intent of the modifications.  The styling of the share links is at line 2100-2130 in the CSS file.  Commenting out line 2107-2108 (left and right positioning) results in the copy button overlaying the share text, which may be the intended UI (though the default text should be transparent, showing on hover).
![share](https://cloud.githubusercontent.com/assets/1319289/12922012/ca9a4a90-cf1d-11e5-84b9-b54466ca4713.png)

**Comment by mbarrenechea** [comment]
I don't see anything wrong...

![image](https://cloud.githubusercontent.com/assets/8928965/13402919/cefb1b82-df12-11e5-88d0-1ac7880c00e6.png)

**Comment by astrong19** [comment]
Thanks! Must have been fixed with Friday's deploy. Closing the issue
